<a href="https://colab.research.google.com/github/siyam-rabail4002/AI-WITH-SVTTI/blob/main/assignment_dataprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv('/content/data_processing_sample.csv')

In [3]:
df.head(

)

    Name   Age  Marks
0    Ali  22.0   85.0
1   Sara  21.0   90.0
2  Ahmed   NaN   78.0
3   Zain  24.0    NaN
4   Sara  21.0   90.0

In [4]:
df.shape

(10, 3)

In [6]:
df=df.drop_duplicates()
df

     Name   Age  Marks
0     Ali  22.0   85.0
1    Sara  21.0   90.0
2   Ahmed   NaN   78.0
3    Zain  24.0    NaN
5    Hina  23.0   88.0
6     NaN  22.0   75.0
7   Usman   NaN   80.0
9  Fatima  25.0    NaN

In [10]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Marks'].fillna(df['Marks'].mean(),inplace=True)
df

/tmp/ipykernel_755/763505751.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
/tmp/ipykernel_755/763505751.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].fillna(df['Marks'].mean(),inplace=True)

     Name        Age      Marks
0     Ali  22.000000  85.000000
1    Sara  21.000000  90.000000
2   Ahmed  22.833333  78.000000
3    Zain  24.000000  82.666667
5    Hina  23.000000  88.000000
6     NaN  22.000000  75.000000
7   Usman  22.833333  80.000000
9  Fatima  25.000000  82.666667